### PR TITLE
icon.ico

### PR DESCRIPTION
**Pull request by JoHnTsIm**
i have put the files just were they were, gui.py inside the pdf2docx and i just add the icon.ico, that needs in order for the gui.py to work

### CODE REVIEW

**Comment by dothinking** [comment]
Thanks for including the icon. I'd prefer your previous commit, a new folder like `gui`, for all user interface related codes. I can do it when get time to this topic, in addition to the suggestion below in my mind:

- when convert multi-files, how about same docx name to source pdf file, e.g. sample.pdf -> sample.docx, rather than doc1.docx, doc2.docx?

p.s. you needn't to close a PR and create a new one for every change. Actually, any new updates in your `JoHnTsIm:gui` branch will automatically reflect here. So, we can discuss and update a same topic iteratively in one PR, for better issue track.

**Comment by JoHnTsIm** [comment]
Thank you for your reply, im gonna try your suggestion, If I succeed, I will let you know. i have already put another pop up window when the convert its successfull.

**Comment by JoHnTsIm** [comment]
i have created a folder with name gui in pdf2docx and i have add the qui.py and the icon.ico, just as you prefer and i believe its better that way to.

**Comment by JoHnTsIm** [comment]
1. when you hit the X Button:
X Button

2. when the convert is completed:
Convert Successfull

**Comment by JoHnTsIm** [comment]
in the knowning issues -> with same name as the converted file and extension .docx

Knowing Issues:
1. If there there is a file in this folder, that the user has choose for converted files save location, with the same name as the converted file its gonna be replaced with the converted file.

**Comment by dothinking** [comment]
Approved, with also the following changes:

- organized the codes in object-oriented programming mode, so can benefit for further maintain since the file is getting bigger.
- switch all user defined msg windows to built-in message box
- fixed `removesuffix` error since it's a python 3.9+ method, while we should support 3.6+.
    ```
    AttributeError: 'str' object has no attribute 'removesuffix'
    ```
- fixed display issue in select docx folder entry: if select docx folder multi-times, the path is combined, rather than replaced.
- Line 23 `Tk().withdraw()` is of no use, in this case, you should use `root.withdraw()` to hide the main gui temporarily and don't forget to show it back with `root.deiconify()` no matter files were selected or not.  I don't think it's unnecessary to, so I deleted it.

Now, it's integrated into ``pdf2docx`` CLI, i.e. type `pdf2docx gui` in the command window to call this GUI. Of course, it's not released yet, but you can try it by installing the dev branch if you like to.

**Comment by dothinking** [comment]
> Knowing Issues: If there there is a file in this folder, that the user has choose for converted files save location, with the same name as the converted file its gonna be replaced with the converted file.

I added a question message box for the user to decide to continue or not. Won't display this message box if no duplicated files exist.

One known issue on "quit" the app by clicking the X at top-right corner:

With the version `sys.exit()`, the app might lose response: click "select pdf files" button to select any file, then do nothing, just to close the window.

So, I changed to `root.destroy()` to terminate the event loop. This avoids losing response, and the app quits immediately, but it takes very long time, say 3~4 minutes, for the command line window to get focus again.

**Comment by dothinking** [comment]
Since the code was merged and I also made some changes, your `gui` branch should fall behind. In case further development from your side, you need to catch up with the latest code, i.e. my `dev` branch, and apply your change based on it, finally pull a merge request back to my `master` branch as you did.

It'd be flexible if you use git, but you still can do it with Github gui, e.g. fetch the latest code

image

Then update your code and pull request just like you did these days.

**Comment by JoHnTsIm** [comment]
Great Job, i have take a look, on your final version and functions, for me at least, exactly as i have in my mind. For now i dont have any more improvment to do, when and if have something, i will let you know.

**Pull request merged**
