### PR TITLE
Added Fix for UnrecognizedImageError

### PR DESCRIPTION
**Pull request by vinduja76**

### CODE REVIEW

**Comment by vinduja76** [comment]
Hi
This is my first ever attempt to open source contribution. Looking forward to it

**Comment by dothinking** [comment]
Nice fix. I just turned around on this issue hours ago, and committed also a [fix](https://github.com/dothinking/pdf2docx/commit/476f07c610e106609bb3c3acf2d83e7cf01398a6) with same idea -> converting to standard image in advance. The different thing is that I do the conversion with `PyMuPDF` , while `pillow` in your fix.

For now, `pillow` seems an overkill, so I'd prefer `PyMuPDF` since it's already a primary requirement of this library.

```python
@property
def image(self):
    '''Get the image bytes converted by PyMuPDF.

        The image bytes are existed already in the raw dict, but there is risk facing
        `docx.image.exceptions.UnrecognizedImageError` when recreate image with python-docx.
        As explained in link below:
        https://stackoverflow.com/questions/56405003/unrecognizedimageerror-image-insertion-error-python-docx

        The solution is to convert to bitmap with PyMuPDF in advance.
    '''
    return fitz.Pixmap(self._image).getImageData(output="png") # convert to png image
```

**Comment by vinduja76** [comment]
Got it. Thanks for your review!!!

**Comment by dothinking** [comment]
Thanks and welcome for your contribution!

For now, I'm to close this PR if not mind.

**Comment by vinduja76** [comment]
I have closed the PR. 
In the Readme file under limitations it states "Text-based PDF file only" which needs to updated right?

**Comment by dothinking** [comment]
To be honest, I have no such plan due to lack of experience. But it'll be much appreciated and welcom if you can turn this limitation to a new feature.

**Pull request closed without merging**
