### PR TITLE
User Interface for the program

### PR DESCRIPTION
**Pull request by JoHnTsIm**
I create user interface for the program with tkinter (5 buttons). 1 for select the pdf file or files (i tried as far as 3 files with one, but im pretty sure that you can convert as much as you like. After the convert, the program saves the new docx files as Docx1.docx, Docx2.docx...), 1 to select the folder in which all files will be saved after the convert, The convert button and finally the quit button (i have put the quit button, because when I pressed the button X on the window, the python code was still running in the background, so i put the quit button to be sure that the program will stop running) and i have put one last button that say 'how to check my file', with the press of this button the program send the user to a page that, saw him how to check, if file of his is text based pdf or image based pdf. I have add and a label with text 'This converter can only convert text based pdf - cant convert image based pdf'.

Here is an image of the User Interface (Has been tested on Windows 10 Machine and Python 3.9):
image

Here is the code:
```ruby
from pdf2docx import *
from tkinter import *
from tkinter.filedialog import *
from tkinter import filedialog
import sys
import webbrowser

root = Tk()
root.title('PDF_2_Docx Converter')
root.geometry('500x700')
root.config(bg='grey')
root.iconbitmap('icon.ico')


# Opens file explorer 
# and let you select choose the pdf file that you want to convert 
def pdf_file_location():
    global filenames
    Tk().withdraw()
    filenames = askopenfilenames()
    file_path_pdf_entry.insert(0, filenames)


# Opens file explorer 
# and let you choose the folder, that all the converted file or files going to saved.
def docx_folder_location():
    global folder_selected
    after_convert_folder = filedialog.askdirectory()
    Tk().withdraw()
    folder_selected = after_convert_folder
    file_path_docx_entry.insert(0, folder_selected)


# Starts the convert of the file or files
def convert_button_function():
    number_of_the_file = 0
    for file in filenames:
        number_of_the_file += 1
        cv = Converter(file)
        cv.convert(folder_selected + '/' + 'Docx' + str(number_of_the_file) + '.docx', start=0, end=None)
        cv.close()


# Close the program window
def close_window():
    sys.exit()


# take you to a webpage, to tell you, how to check your file or files
def callback():
    webbrowser.open_new(r"https://support.policystat.com/hc/en-us/articles"
                        r"/207993346-How-can-I-tell-if-my-PDFs-are-text-based-or-not-")


"""Labels"""

program_use_label = Label(text='PDF to Docx', font='Impact 40', bg='white', fg='#1E90FF')
program_use_label.grid(column=2, row=1, sticky='n', pady=50, padx=120)

check_label = Label(text='*This converter can only convert text based pdf \n cant convert image based pdf',
                    bg='grey')
check_label.grid(row=7, column=2, pady=10)


"""Entries"""

# PDF file entry
file_path_pdf_entry = Entry(border=5)
file_path_pdf_entry.grid(ipadx=90, ipady=4, padx=20, sticky='nw', column=2, pady=1, row=2)

# Docx file entry
file_path_docx_entry = Entry(border=5)
file_path_docx_entry.grid(column=2, ipady=4, ipadx=90, padx=20, sticky='nw', pady=70, row=3)


"""Buttons"""

converter_button = Button(text='Convert', bg='#1E90FF', fg='white', font='impact 20', border=5,
                          command=convert_button_function)
converter_button.grid(padx=175, sticky='s', ipady=5, ipadx=10, column=2, row=4)

select_pdf_file = Button(text='Select PDF file', fg='black', bg='white', border=3,
                         command=pdf_file_location)
select_pdf_file.grid(column=2, sticky='ne', row=2, pady=6, padx=60)

select_new_file_folder = Button(text='Select new file folder', fg='black', bg='white', border=3,
                                command=docx_folder_location)
select_new_file_folder.grid(column=2, sticky='ne', row=3, pady=74, padx=26)

quit_button = Button(text='Quit', bg='#1E90FF', fg='white', font='impact 20', border=5, command=close_window)
quit_button.grid(row=6, column=2, pady=30, ipadx=30)

difference_button = Button(text='how to check my file?', bg='grey', fg='black', command=callback)
difference_button.grid(column=2)

root.mainloop()
```

### CODE REVIEW

**Comment by dothinking** [comment]
Many thanks for your contribution. 

It seems you're new to GitHub, this post will guide you [how to create a github pull request](http://www.dasblinkenlichten.com/how-to-create-a-github-pull-request-pr/). In this way, it'd be convenient for you to push your  code directly, rather than post code here, if any further improvement.

Anyway, that is optional if you prefer not to. I've created a branch `gui` for this topic. For now,  your initial code is included, later on I'll integrate it to the command line interface, like `pdf2docx gui` to start this UI, and finally merge it to the `master` branch.

https://github.com/dothinking/pdf2docx/blob/gui/pdf2docx/gui.py

**Comment by JoHnTsIm** [comment]
I wil give a look on the github pull request guide, thanks for the unterstanding. i will make a little bit more improvments on the gui and then i will post the code on the right place this time.

**Comment by dothinking** [comment]
> 1 for select the pdf file or files (i tried as far as 3 files with one, but im pretty sure that you can convert as much as you like.

Very good. Multiple selection will make this tool more convenient.

 > i have put the quit button, because when I pressed the button X on the window, the python code was still running in the background

Yes, I also found this issue with your initial version of code. Now it looks good.

>  I have add and a label with text 'This converter can only convert text based pdf - cant convert image based pdf'.

Good point.

Thank you for your contribution again!

**Comment by JoHnTsIm** [comment]
If the user has chosen to save the converted files, in a folder in which he has his own kind of files, make sure that there is no docx file named Docx1, 2, 3... Ιn order to avoid the risk of replacing his own files, with the converted files. For sure I would suggest choosing an empty folder.

**Pull request closed without merging**
